import oracledb
import os
import array
from langchain_cohere import CohereEmbeddings
from dotenv import load_dotenv
import json

load_dotenv()
my_key = os.getenv("COHERE_API_KEY")

os.environ["COHERE_API_KEY"] = my_key

#DATABASE CREDENTIALS
DB_USER = "sys"
DB_PWD = "mypassword"  # The password you set in the docker command
# NEW (DevOps Friendly)
# If 'DB_DSN' env var exists (Docker), use it. If not, default to localhost (Laptop).
DB_DSN = os.getenv("DB_DSN", "localhost:1521/FREEPDB1")

#SETTING UP CONNECTION
print("Connecting to database...")
try:
    conn = oracledb.connect(
        user=DB_USER,
        password=DB_PWD,
        dsn=DB_DSN,
        mode=oracledb.SYSDBA 
    )
    cursor = conn.cursor()
    print("✅ Connected to Oracle Database 23ai!")
except Exception as e:
    print(f"❌ Connection Failed: {e}")

#creating table
#first we drop any table
try:
    cursor.execute("DROP TABLE diet_vectors PURGE")
    print("Old table dropped")
except:
    pass

#create table with VECTOR data type(1024 dims for cohere)
cursor.execute("""
    CREATE TABLE diet_vectors (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            content VARCHAR2(4000),
            v_embedding VECTOR(1024, FLOAT64)
        )      
""")
print("SiO table 'diet_vectors' created.")

#Loading data form JSON FILE
try:
    with open('data.json', 'r') as f:
        data=json.load(f)
    print("Data loaded from data.json")
except Exception as e:
    print(f"❌ Failed to load data: {e}")
    exit()

#Inserting data into table and embedding
embeddings = CohereEmbeddings(model="embed-english-v3.0")
print(f"🧠 Processing {len(data)} regions...")

for item in data:
    #flattening json list into text
    #creating one big string containing all the info of that region.
    rich_text = f"""
    Region: {item['region']}

    General Guidelines:
    {item['content']}

    Breakfast Recommendations:
    - " + "\n- ".join(item['breakfast']) + "

    Lunch Recommendations:
    - " + "\n- ".join(item['lunch']) + "

    Dinner Recommendations:
    - " + "\n- ".join(item['dinner']) + "

    High-Sugar / Foods to Avoid (Unsuitable for Diabetes):
    - " + "\n- ".join(item['high_sugar_foods']) + "

    Low-Sugar / Safe Foods for Diabetes:
    - " + "\n- ".join(item['low_sugar_foods']) + "

    """
    #cleaning up rich text
    rich_text = " ".join(rich_text.split())

    #embedding now
    vec_list = embeddings.embed_query(rich_text)
    vec_data = array.array("d",vec_list)

    cursor.execute(
        "INSERT INTO diet_vectors (content, v_embedding) VALUES (:1, :2)",
        [rich_text, vec_data]
        )

conn.commit()
print("✅ All data inserted and embedded successfully!")    

cursor.close()
conn.close()
